name: System Information

on:
  workflow_dispatch:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make system script executable
        run: chmod +x scripts/system-check.sh

      - name: Run system check
        id: syscheck
        run: ./scripts/system-check.sh

      - name: Show disk usage result
        run: echo "Disk usage is ${{ steps.syscheck.outputs.DISK_USAGE }}%"

      - name: Run uptime check
        run: |
          chmod +x scripts/uptime-check.sh
          ./scripts/uptime-check.sh

      - name: Upload system report
        uses: actions/upload-artifact@v4
        with:
          name: system-report
          path: report.txt

      - name: Upload uptime report
        uses: actions/upload-artifact@v4
        with:
          name: uptime-report
          path: uptime-report.txt

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-learning .

      - name: Run container
        run: docker run -d -p 8080:80 --name test-container github-learning

      - name: Wait for container to start
        run: sleep 5

      - name: Test web server
        run: curl -f http://localhost:8080

      - name: Stop container
        run: docker stop test-container