name: System Information

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/system-check.sh

      - name: Run system check script
        run: ./scripts/system-check.sh

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-report
          path: report.txt